project:
  type: website

website:
  sidebar:
    background: "#4a6fa5"
    style: "docked"
    search: true
    contents:
      - text: "About me"
        href: index.qmd
      - section: "Causal inference"
        contents: 
          - contents/causal_inference/causal.qmd
     


format: 
  html:
    css: styles.css
    toc: true



