project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        href: index.qmd
     


# website:
#   title: "kai_personal_site"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - about.qmd

format: 
  html:
    css: styles.css
    toc: true



