project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        href: index.qmd
     


format: 
  html:
    css: styles.css
    toc: true



