project:
  type: website

website:
  bread-crumbs: true
  sidebar:
    background: "#4a6fa5"
    collapse-level: 1
    style: "docked"
    search: true
    contents:
      - text: "About me"
        href: index.qmd
      - section: "My PhD projects"
        contents: 
          - contents/phd_projects/ted-self-harm.qmd
      - section: "Causal inference"
        contents: 
          - contents/causal_inference/causal.qmd
          - contents/causal_inference/causal_generative_model.qmd
     


format:
  html:
    css: styles.css
    toc: true




